version: '3'
services:
  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - '8500:8500'
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=byte_go
    volumes:
      - ./deploy/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml