version: '3.8'
services:
  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - '8500:8500'
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=byte_go
    volumes:
      - ./deploy/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pbyte_go"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml
  frontend:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-frontend
#    image: byte_go-frontend:latest
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=rule
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/frontend/conf:/opt/byte_go/frontend/conf
      - ./app/frontend/log:/opt/byte_go/frontend/log
      - ./app/frontend/casbin/model.pml:/opt/byte_go/frontend/casbin/model.pml
  auth:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=auth
    environment:
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - ./app/auth/conf:/opt/byte_go/auth/conf
      - ./app/auth/log:/opt/byte_go/auth/log
  cart:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=cart
    environment:
      - GO_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=cart
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app/cart/conf:/opt/byte_go/cart/conf
      - ./app/cart/log:/opt/byte_go/cart/log
  checkout:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=checkout
    environment:
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
    volumes:
      - ./app/checkout/conf:/opt/byte_go/checkout/conf
      - ./app/checkout/log:/opt/byte_go/checkout/log
  order:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=order
    environment:
      - GO_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=order
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app/order/conf:/opt/byte_go/order/conf
      - ./app/order/log:/opt/byte_go/order/log
  payment:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=payment
    environment:
      - GO_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=payment
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app/payment/conf:/opt/byte_go/payment/conf
      - ./app/payment/log:/opt/byte_go/payment/log
  product:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=product
    container_name: byte_go-product
    image: byte_go-product:latest
    environment:
      - GO_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=product
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app/product/conf:/opt/byte_go/product/conf
      - ./app/product/log:/opt/byte_go/product/log
  user:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile-svc
      args:
        - SVC=user
    container_name: byte_go-user
    image: byte_go-user:latest
    environment:
      - GO_ENV=dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=byte_go
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=user
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app/user/conf:/opt/byte_go/user/conf
      - ./app/user/log:/opt/byte_go/user/log
