version: '3'
services:
  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - '8500:8500'
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=byte_go
      - MYSQL_DATABASE=user
      - MYSQL_DATABASE=cart
      - MYSQL_DATABASE=product
      - MYSQL_DATABASE=order
      - MYSQL_DATABASE=rule
      - MYSQL_DATABASE=payment
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
