// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}
