// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
