// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "byte_go/backend/app/front/biz/router/cart"
	order "byte_go/backend/app/front/biz/router/order"
	product "byte_go/backend/app/front/biz/router/product"
	user "byte_go/backend/app/front/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	cart.Register(r)

	product.Register(r)

	user.Register(r)
}
