// Code generated by hertz generator.

package cart

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _additemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emptycartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcartMw() []app.HandlerFunc {
	// your code...
	return nil
}
